export type CountryDialCode = {
  iso: string;
  label: string;
  code: string;
  flag: string;
};

function countryFlag(iso: string): string {
  return iso
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}

const RAW_COUNTRY_DIAL_CODES: Array<{ iso: string; label: string; code: string }> = [
  { iso: "AF", label: "Afghanistan", code: "+93" },
  { iso: "AL", label: "Albania", code: "+355" },
  { iso: "DZ", label: "Algeria", code: "+213" },
  { iso: "AS", label: "American Samoa", code: "+1" },
  { iso: "AD", label: "Andorra", code: "+376" },
  { iso: "AO", label: "Angola", code: "+244" },
  { iso: "AI", label: "Anguilla", code: "+1" },
  { iso: "AG", label: "Antigua and Barbuda", code: "+1" },
  { iso: "AR", label: "Argentina", code: "+54" },
  { iso: "AM", label: "Armenia", code: "+374" },
  { iso: "AW", label: "Aruba", code: "+297" },
  { iso: "AU", label: "Australia", code: "+61" },
  { iso: "AT", label: "Austria", code: "+43" },
  { iso: "AZ", label: "Azerbaijan", code: "+994" },
  { iso: "BS", label: "Bahamas", code: "+1" },
  { iso: "BH", label: "Bahrain", code: "+973" },
  { iso: "BD", label: "Bangladesh", code: "+880" },
  { iso: "BB", label: "Barbados", code: "+1" },
  { iso: "BY", label: "Belarus", code: "+375" },
  { iso: "BE", label: "Belgium", code: "+32" },
  { iso: "BZ", label: "Belize", code: "+501" },
  { iso: "BJ", label: "Benin", code: "+229" },
  { iso: "BM", label: "Bermuda", code: "+1" },
  { iso: "BT", label: "Bhutan", code: "+975" },
  { iso: "BO", label: "Bolivia", code: "+591" },
  { iso: "BA", label: "Bosnia and Herzegovina", code: "+387" },
  { iso: "BW", label: "Botswana", code: "+267" },
  { iso: "BR", label: "Brazil", code: "+55" },
  { iso: "BN", label: "Brunei", code: "+673" },
  { iso: "BG", label: "Bulgaria", code: "+359" },
  { iso: "BF", label: "Burkina Faso", code: "+226" },
  { iso: "BI", label: "Burundi", code: "+257" },
  { iso: "KH", label: "Cambodia", code: "+855" },
  { iso: "CM", label: "Cameroon", code: "+237" },
  { iso: "CA", label: "Canada", code: "+1" },
  { iso: "CV", label: "Cape Verde", code: "+238" },
  { iso: "KY", label: "Cayman Islands", code: "+1" },
  { iso: "CF", label: "Central African Republic", code: "+236" },
  { iso: "TD", label: "Chad", code: "+235" },
  { iso: "CL", label: "Chile", code: "+56" },
  { iso: "CN", label: "China", code: "+86" },
  { iso: "CO", label: "Colombia", code: "+57" },
  { iso: "KM", label: "Comoros", code: "+269" },
  { iso: "CG", label: "Congo", code: "+242" },
  { iso: "CD", label: "Congo (DRC)", code: "+243" },
  { iso: "CK", label: "Cook Islands", code: "+682" },
  { iso: "CR", label: "Costa Rica", code: "+506" },
  { iso: "CI", label: "Côte d'Ivoire", code: "+225" },
  { iso: "HR", label: "Croatia", code: "+385" },
  { iso: "CU", label: "Cuba", code: "+53" },
  { iso: "CY", label: "Cyprus", code: "+357" },
  { iso: "CZ", label: "Czech Republic", code: "+420" },
  { iso: "DK", label: "Denmark", code: "+45" },
  { iso: "DJ", label: "Djibouti", code: "+253" },
  { iso: "DM", label: "Dominica", code: "+1" },
  { iso: "DO", label: "Dominican Republic", code: "+1" },
  { iso: "EC", label: "Ecuador", code: "+593" },
  { iso: "EG", label: "Egypt", code: "+20" },
  { iso: "SV", label: "El Salvador", code: "+503" },
  { iso: "GQ", label: "Equatorial Guinea", code: "+240" },
  { iso: "ER", label: "Eritrea", code: "+291" },
  { iso: "EE", label: "Estonia", code: "+372" },
  { iso: "SZ", label: "Eswatini", code: "+268" },
  { iso: "ET", label: "Ethiopia", code: "+251" },
  { iso: "FJ", label: "Fiji", code: "+679" },
  { iso: "FI", label: "Finland", code: "+358" },
  { iso: "FR", label: "France", code: "+33" },
  { iso: "GF", label: "French Guiana", code: "+594" },
  { iso: "PF", label: "French Polynesia", code: "+689" },
  { iso: "GA", label: "Gabon", code: "+241" },
  { iso: "GM", label: "Gambia", code: "+220" },
  { iso: "GE", label: "Georgia", code: "+995" },
  { iso: "DE", label: "Germany", code: "+49" },
  { iso: "GH", label: "Ghana", code: "+233" },
  { iso: "GI", label: "Gibraltar", code: "+350" },
  { iso: "GR", label: "Greece", code: "+30" },
  { iso: "GL", label: "Greenland", code: "+299" },
  { iso: "GD", label: "Grenada", code: "+1" },
  { iso: "GP", label: "Guadeloupe", code: "+590" },
  { iso: "GU", label: "Guam", code: "+1" },
  { iso: "GT", label: "Guatemala", code: "+502" },
  { iso: "GN", label: "Guinea", code: "+224" },
  { iso: "GW", label: "Guinea-Bissau", code: "+245" },
  { iso: "GY", label: "Guyana", code: "+592" },
  { iso: "HT", label: "Haiti", code: "+509" },
  { iso: "HN", label: "Honduras", code: "+504" },
  { iso: "HK", label: "Hong Kong", code: "+852" },
  { iso: "HU", label: "Hungary", code: "+36" },
  { iso: "IS", label: "Iceland", code: "+354" },
  { iso: "IN", label: "India", code: "+91" },
  { iso: "ID", label: "Indonesia", code: "+62" },
  { iso: "IR", label: "Iran", code: "+98" },
  { iso: "IQ", label: "Iraq", code: "+964" },
  { iso: "IE", label: "Ireland", code: "+353" },
  { iso: "IL", label: "Israel", code: "+972" },
  { iso: "IT", label: "Italy", code: "+39" },
  { iso: "JM", label: "Jamaica", code: "+1" },
  { iso: "JP", label: "Japan", code: "+81" },
  { iso: "JO", label: "Jordan", code: "+962" },
  { iso: "KZ", label: "Kazakhstan", code: "+7" },
  { iso: "KE", label: "Kenya", code: "+254" },
  { iso: "KI", label: "Kiribati", code: "+686" },
  { iso: "XK", label: "Kosovo", code: "+383" },
  { iso: "KW", label: "Kuwait", code: "+965" },
  { iso: "KG", label: "Kyrgyzstan", code: "+996" },
  { iso: "LA", label: "Laos", code: "+856" },
  { iso: "LV", label: "Latvia", code: "+371" },
  { iso: "LB", label: "Lebanon", code: "+961" },
  { iso: "LS", label: "Lesotho", code: "+266" },
  { iso: "LR", label: "Liberia", code: "+231" },
  { iso: "LY", label: "Libya", code: "+218" },
  { iso: "LI", label: "Liechtenstein", code: "+423" },
  { iso: "LT", label: "Lithuania", code: "+370" },
  { iso: "LU", label: "Luxembourg", code: "+352" },
  { iso: "MO", label: "Macau", code: "+853" },
  { iso: "MG", label: "Madagascar", code: "+261" },
  { iso: "MW", label: "Malawi", code: "+265" },
  { iso: "MY", label: "Malaysia", code: "+60" },
  { iso: "MV", label: "Maldives", code: "+960" },
  { iso: "ML", label: "Mali", code: "+223" },
  { iso: "MT", label: "Malta", code: "+356" },
  { iso: "MH", label: "Marshall Islands", code: "+692" },
  { iso: "MQ", label: "Martinique", code: "+596" },
  { iso: "MR", label: "Mauritania", code: "+222" },
  { iso: "MU", label: "Mauritius", code: "+230" },
  { iso: "MX", label: "Mexico", code: "+52" },
  { iso: "FM", label: "Micronesia", code: "+691" },
  { iso: "MD", label: "Moldova", code: "+373" },
  { iso: "MC", label: "Monaco", code: "+377" },
  { iso: "MN", label: "Mongolia", code: "+976" },
  { iso: "ME", label: "Montenegro", code: "+382" },
  { iso: "MS", label: "Montserrat", code: "+1" },
  { iso: "MA", label: "Morocco", code: "+212" },
  { iso: "MZ", label: "Mozambique", code: "+258" },
  { iso: "MM", label: "Myanmar", code: "+95" },
  { iso: "NA", label: "Namibia", code: "+264" },
  { iso: "NR", label: "Nauru", code: "+674" },
  { iso: "NP", label: "Nepal", code: "+977" },
  { iso: "NL", label: "Netherlands", code: "+31" },
  { iso: "NC", label: "New Caledonia", code: "+687" },
  { iso: "NZ", label: "New Zealand", code: "+64" },
  { iso: "NI", label: "Nicaragua", code: "+505" },
  { iso: "NE", label: "Niger", code: "+227" },
  { iso: "NG", label: "Nigeria", code: "+234" },
  { iso: "NU", label: "Niue", code: "+683" },
  { iso: "NF", label: "Norfolk Island", code: "+672" },
  { iso: "KP", label: "North Korea", code: "+850" },
  { iso: "MK", label: "North Macedonia", code: "+389" },
  { iso: "NO", label: "Norway", code: "+47" },
  { iso: "OM", label: "Oman", code: "+968" },
  { iso: "PK", label: "Pakistan", code: "+92" },
  { iso: "PW", label: "Palau", code: "+680" },
  { iso: "PS", label: "Palestine", code: "+970" },
  { iso: "PA", label: "Panama", code: "+507" },
  { iso: "PG", label: "Papua New Guinea", code: "+675" },
  { iso: "PY", label: "Paraguay", code: "+595" },
  { iso: "PE", label: "Peru", code: "+51" },
  { iso: "PH", label: "Philippines", code: "+63" },
  { iso: "PL", label: "Poland", code: "+48" },
  { iso: "PT", label: "Portugal", code: "+351" },
  { iso: "PR", label: "Puerto Rico", code: "+1" },
  { iso: "QA", label: "Qatar", code: "+974" },
  { iso: "RE", label: "Réunion", code: "+262" },
  { iso: "RO", label: "Romania", code: "+40" },
  { iso: "RU", label: "Russia", code: "+7" },
  { iso: "RW", label: "Rwanda", code: "+250" },
  { iso: "KN", label: "Saint Kitts and Nevis", code: "+1" },
  { iso: "LC", label: "Saint Lucia", code: "+1" },
  { iso: "VC", label: "Saint Vincent and the Grenadines", code: "+1" },
  { iso: "WS", label: "Samoa", code: "+685" },
  { iso: "SM", label: "San Marino", code: "+378" },
  { iso: "ST", label: "São Tomé and Príncipe", code: "+239" },
  { iso: "SA", label: "Saudi Arabia", code: "+966" },
  { iso: "SN", label: "Senegal", code: "+221" },
  { iso: "RS", label: "Serbia", code: "+381" },
  { iso: "SC", label: "Seychelles", code: "+248" },
  { iso: "SL", label: "Sierra Leone", code: "+232" },
  { iso: "SG", label: "Singapore", code: "+65" },
  { iso: "SK", label: "Slovakia", code: "+421" },
  { iso: "SI", label: "Slovenia", code: "+386" },
  { iso: "SB", label: "Solomon Islands", code: "+677" },
  { iso: "SO", label: "Somalia", code: "+252" },
  { iso: "ZA", label: "South Africa", code: "+27" },
  { iso: "KR", label: "South Korea", code: "+82" },
  { iso: "SS", label: "South Sudan", code: "+211" },
  { iso: "ES", label: "Spain", code: "+34" },
  { iso: "LK", label: "Sri Lanka", code: "+94" },
  { iso: "SD", label: "Sudan", code: "+249" },
  { iso: "SR", label: "Suriname", code: "+597" },
  { iso: "SE", label: "Sweden", code: "+46" },
  { iso: "CH", label: "Switzerland", code: "+41" },
  { iso: "SY", label: "Syria", code: "+963" },
  { iso: "TW", label: "Taiwan", code: "+886" },
  { iso: "TJ", label: "Tajikistan", code: "+992" },
  { iso: "TZ", label: "Tanzania", code: "+255" },
  { iso: "TH", label: "Thailand", code: "+66" },
  { iso: "TL", label: "Timor-Leste", code: "+670" },
  { iso: "TG", label: "Togo", code: "+228" },
  { iso: "TO", label: "Tonga", code: "+676" },
  { iso: "TT", label: "Trinidad and Tobago", code: "+1" },
  { iso: "TN", label: "Tunisia", code: "+216" },
  { iso: "TR", label: "Turkey", code: "+90" },
  { iso: "TM", label: "Turkmenistan", code: "+993" },
  { iso: "TC", label: "Turks and Caicos Islands", code: "+1" },
  { iso: "TV", label: "Tuvalu", code: "+688" },
  { iso: "UG", label: "Uganda", code: "+256" },
  { iso: "UA", label: "Ukraine", code: "+380" },
  { iso: "AE", label: "United Arab Emirates", code: "+971" },
  { iso: "GB", label: "United Kingdom", code: "+44" },
  { iso: "US", label: "United States", code: "+1" },
  { iso: "UY", label: "Uruguay", code: "+598" },
  { iso: "UZ", label: "Uzbekistan", code: "+998" },
  { iso: "VU", label: "Vanuatu", code: "+678" },
  { iso: "VA", label: "Vatican City", code: "+39" },
  { iso: "VE", label: "Venezuela", code: "+58" },
  { iso: "VN", label: "Vietnam", code: "+84" },
  { iso: "VG", label: "Virgin Islands (British)", code: "+1" },
  { iso: "VI", label: "Virgin Islands (U.S.)", code: "+1" },
  { iso: "YE", label: "Yemen", code: "+967" },
  { iso: "ZM", label: "Zambia", code: "+260" },
  { iso: "ZW", label: "Zimbabwe", code: "+263" },
];

const PRIORITY_ISOS = [
  "IN",
  "US",
  "GB",
  "AE",
  "SA",
  "QA",
  "BH",
  "OM",
  "KW",
  "KE",
  "NG",
  "ZA",
  "EG",
  "ET",
  "TZ",
  "UG",
  "RW",
  "GH",
  "GN",
  "SL",
  "BI",
  "SS",
  "SO",
  "DE",
  "FR",
  "AU",
  "SG",
  "CA",
];

const withFlags = RAW_COUNTRY_DIAL_CODES.map((entry) => ({
  ...entry,
  flag: countryFlag(entry.iso),
}));

const prioritySet = new Set(PRIORITY_ISOS);

export const countryDialCodes: CountryDialCode[] = [
  ...PRIORITY_ISOS.map((iso) => withFlags.find((entry) => entry.iso === iso)).filter(
    (entry): entry is CountryDialCode => Boolean(entry)
  ),
  ...withFlags
    .filter((entry) => !prioritySet.has(entry.iso))
    .sort((a, b) => a.label.localeCompare(b.label)),
];

export const countryNames = withFlags.map((entry) => entry.label).sort((a, b) => a.localeCompare(b));

export function getDialCodeByIso(iso: string): string {
  return countryDialCodes.find((entry) => entry.iso === iso)?.code ?? "+91";
}

export const DEFAULT_COUNTRY_ISO = "IN";
