import type { ServiceDetailTemplateProps } from "@/components/ServiceDetailTemplate";

export const servicePages: Record<string, ServiceDetailTemplateProps> = {
  businessTechnical: {
    title: "Business & Technical Consultancy",
    subtitle: "Your Industrial Think Tank for comprehensive business and technical solutions.",
    image: "/service-details/business-technical-consultancy.jpg",
    imageAlt: "Business and Technical Consultancy",
    introTitle: "Business and Technical Consultancy",
    highlight: "We are Your Industrial Think Tank!",
    introParagraphs: [
      "Avconexpo delivers Business and Technical solutions tailored to your needs. We are problem solvers, strategists, and partners in driving you to success by building a comprehensive plan of action tailored to your industrial needs, leveraging our pool of technical experts.",
      "We provide end-to-end solutions for Greenfield and Brownfield projects from Scratch to Shelf and Concept to Consumer with the help of our pool of Consultants, Architects, Engineers, Energy Conservators and Other Professionals for industrial projects, plant setups, infrastructural development, and process optimization using the latest engineering and technological advancements.",
      "Our technical experts bring forth their expertise and experience in designing, building, sourcing, operating, and maintaining products and services in their respective industries and markets.",
    ],
    sections: [
      {
        eyebrow: "Our Approach",
        title: "Our Process / Approach",
        blocks: [
          { title: "Conceptualization", description: "Project conceptualization is the initial process of designing a project, leading to project concept documents. The project concept is the basis on which the interest of potential investors is secured." },
          { title: "Feasibility Study", description: "Our feasibility study gives an in-depth overview of the viability of the project.", items: ["Market Viability", "Technical Viability", "Business Model Viability", "Management Model Viability", "Economic and Financial Model Viability", "Exit Strategy Viability"] },
          { title: "Compatibility Study", description: "We ascertain the competency/capability of an Entrepreneur/Firm for the project and evaluate strategic importance, process maturity, resources, IT support, and cost factors." },
          { title: "Risk Assessment", description: "We identify tangential and non-tangential risks, determine severity, and explore solutions that reduce the impact of those risks." },
          { title: "Business / Project Proposal", description: "We provide comprehensive documentation covering all bankable, technical, financial, and 5-year commercial aspects of the business or project." },
          { title: "Capex Arrangement", description: "We provide solutions for capital investment through financial institutions locally as well as internationally." },
          { title: "Execution", description: "We provide project management, vendor management, sourcing, installation, and commissioning services for the right and worthy plants and machines." },
          { title: "Operations & Training", description: "The process involves training local personnel to operate independently within a specified timeline, with the help of experts." },
        ],
      },
      {
        eyebrow: "Integration",
        title: "Complete Factory Integration",
        description: "At Avconexpo, we specialise in assisting in establishing industries and industrial parks, from the initial concept to a fully operational plant.",
        blocks: [
          { title: "Land and Building", items: ["Advising and monitoring land selection, uses, compliance, site survey, and soil Investigation.", "Designing and preparation of the integrated master plan of the complete factory with buildings and warehouses with optimum flow management and ease of operation.", "Advising and monitoring the compliance of land development and buildings.", "Designing and advising on-site protection and firefighting system for a complete setup.", "Advising on construction and building material for warehouses, structures, and foundations.", "Designing and advising on the communication and traffic flow management of man, machine, and material.", "Designing and preparation of detailed drawings for architecture, structure, MEPF, landscaping, and tender documents."] },
          { title: "Plant and Equipment", items: ["Designing technical solutions by pre-project management, technical analysis, and viability assessment.", "Detailed engineering for the latest technology, operational efficiency, and ease of implementation and integration.", "Vendor recommendation, evaluation, and management for technical governance and compliances.", "Monitoring and supervising installation and commissioning till commercial production.", "Arranging, training, and setting up all human resources from operator level to functional heads."] },
          { title: "Electrical, Mechanical, Instrumentation and Ancillaries", items: ["Designing and engineering electrical systems from HT, substation, distribution panels, and power factor.", "Designing, sizing, and preparation of layout for electrical and signal cables, switch gears, control panels, and terminals.", "Designing and engineering earthing grids for humans, machines, and weather.", "Designing on complete lighting of the factory.", "Designing, engineering, and preparing layout for distribution and collection systems of products, steam, chilled water, cold water, water, compressed air, condensate water, effluent, and solid waste.", "Designing and preparation of layouts for pipe bridges, trenches, overpasses, and underpasses."] },
          { title: "Utilities", items: ["Designing, engineering, and advising on material handling and weighing equipment resources.", "Designing and engineering of generation / production plants and equipment for steam, chilled water, cold water, compressed air, water, and effluent.", "Designing and engineering of fire management system with hydrant and extinguisher.", "Designing, engineering, and advising on storage systems including warehouses, silos, and tank farms."] },
        ],
      },
    ],
    closingText: "Whether it is a Greenfield or Brownfield project, we bring deep expertise, proven processes, and the right people to make it happen.",
    ctaLabel: "Discuss Your Project",
  },
  projectManagement: {
    title: "Project Management",
    subtitle: "Comprehensive end-to-end project management for Greenfield, Brownfield, and expansion projects.",
    image: "/service-details/projectmanagement.jpg",
    imageAlt: "Project Management",
    introTitle: "Project Management",
    highlight: "Budget, time, quality, safety",
    introParagraphs: [
      "At Avconexpo, our expertise in project management solutions for Greenfield, Brownfield, and expansion of Projects ensures that your projects are within budget and executed cohesively on time with utmost importance.",
      "We work according to the required standards, ensuring the Law of the Land, keeping in mind OHS, low conversion cost, quality control, and assurance.",
    ],
    sections: [
      {
        eyebrow: "Our Solution",
        title: "Our Project Management Solution",
        description: "We provide comprehensive end-to-end project management services tailored to your specific needs. Our services encompass all necessary aspects of any project.",
        blocks: [
          { title: "Strategic Planning & Project Structuring", items: ["Specify project scope, objectives, and deliverables that align with your project vision.", "Develop detailed project timelines, budgets, and resource deployment plans."] },
          { title: "Pre-Construction & Pre-Sourcing Management", items: ["Manage pre-sourcing of raw materials, machinery, and ancillary equipment.", "Integrate the complete factory with the theme plant to ensure seamless operations and a unified workflow."] },
          { title: "Site and Operations Management", items: ["Monitor all on-site and off-site aspects of execution, namely civil, mechanical, electrical, instrumentation, and utilities.", "Supervise equipment installation, fabrication, construction, and commissioning phases."] },
          { title: "Monitoring, Control & Communication", items: ["Maintain continuous tracking of project milestones, timelines, and costs.", "Manage interactions among clients, consultants, vendors, contractors, regulators, and local authorities to ensure cohesive execution.", "Conduct periodic reviews, site visits, and technical checks in line with industry standards and safety norms."] },
          { title: "OEM and Vendor Management", items: ["Ensure that specialised machinery, equipment, and raw materials are sourced for your project on schedule.", "Handle vendor evaluation, pre-qualification, contract drafting, negotiation, and administration to ensure clarity on scope, costs, and timelines."] },
          { title: "Supply Chain & Logistics Management", items: ["Build an integrated supply chain that covers raw materials, machinery, spares, consumables, and finished goods flow.", "Ensure contracts and logistics operations comply with statutory requirements, international trade regulations, and safety norms."] },
          { title: "Risk and Quality Management", items: ["Implement risk identification and mitigation plans using global best practices such as FMEA, HAZOP, and HACCP.", "Ensure compliance with all applicable laws, regulations, and safety protocols."] },
          { title: "Commissioning & Operational Readiness", items: ["Oversee end-to-end plant commissioning from test runs to full commercial production.", "Provide on-demand assistance for operational support."] },
        ],
      },
    ],
    closingText: "By optimizing resource allocation and adhering to global best practices, Avconexpo helps you achieve seamless execution and long-term success.",
  },
  architecture: {
    title: "Architecture & Designing",
    subtitle: "Design solutions that suit client needs while considering environment, function, comfort, and long-term value.",
    image: "/service-details/architecture.jpg",
    imageAlt: "Architecture and Designing",
    introTitle: "Architecture & Designing",
    highlight: "Concept to creation",
    introParagraphs: [
      "At Avconexpo, our architecture team strives to create design solutions that suit the needs of the client and the community while considering their effects on the environment.",
      "Each design is unique and is made keeping in mind the ancient science of Vaastu to deliver a design that is not only aesthetically pleasing but also beneficial to the client in every aspect - mind, body, and soul.",
    ],
    sections: [
      { eyebrow: "Foundation", title: "Our Design Principles", blocks: [
        { title: "Vaastu Compliant", description: "Vaastu Shastra offers timeless principles for creating homes that promote well-being, prosperity, and happiness." },
        { title: "Climate Responsive Design", description: "Taking into account seasonality, solar pathing, natural shading, ambient humidity, and annual rainfall patterns to provide maximum occupant comfort." },
        { title: "Aesthetic", description: "The appeal of a building covers the combined effects of shape, size, texture, colour, balance, emphasis, contrast, symmetry, and culture." },
        { title: "Environmental Friendly", description: "Building materials, construction methods, resource use, and design that minimize environmental impact." },
        { title: "Pedestrian Friendly", description: "Features like wide sidewalks, crosswalks, green spaces, and integration of pedestrian paths with public transportation." },
        { title: "Human Comfort", description: "Factors like thermal conditions, lighting, acoustics, and indoor air quality." },
      ] },
      { eyebrow: "Philosophy", title: "Our Design Philosophy", blocks: [
        { title: "User Centric Design", description: "Every design is tailored keeping the end user in mind. Spaces should serve a function while evoking comfort, purpose, and belonging." },
        { title: "Innovation with Context", description: "We push boundaries through modern technologies, sustainable materials, and fresh ideas, always in dialogue with site, climate, culture, and budget." },
        { title: "Time Responsive Design", description: "We create architecture that remains relevant, functional, and inspiring over time by responding to sunlight, climate, and daily life." },
        { title: "Function Drives Form", description: "A well-designed building should perform as beautifully as it looks. We prioritize functionality and buildability at every scale." },
        { title: "Design for High Performance", description: "We prioritize passive design strategies to reduce energy consumption and operational costs." },
        { title: "Human Comfort", description: "Thermal conditions, lighting, acoustics, and indoor air quality remain central to the design." },
      ] },
      { eyebrow: "Industrial Design", title: "Industrial Design", paragraphs: ["Our Design team also specializes in designing large-scale spaces like factories, warehouses, or manufacturing units. We plan with purpose, optimizing layouts for machinery, material movement, storage, and staff circulation. Every detail is considered, from ventilation and lighting to structural strength and safety protocols."], blocks: [
        { title: "Efficiency at the Core", description: "Optimizes layouts for smooth workflow, material handling, and employee movement." },
        { title: "Safety First", description: "Prioritizes safety by incorporating fire exits, ventilation, lighting, and proper structural planning." },
        { title: "Expert Planning", description: "In-depth planning for machinery placement, storage systems, and operational flow, tailored to your business needs." },
        { title: "Compliance with Industry Standards", description: "Ensures designs meet all relevant industrial norms, local regulations, and safety standards." },
        { title: "Long-Term Scalability", description: "Designs that accommodate future growth, enabling easy upgrades and expansion as your business evolves." },
        { title: "Practical, Functional Spaces", description: "Focuses on creating spaces that are visually appealing, practical, and functional." },
      ] },
    ],
    closingText: "From factory layouts and process-driven facilities to warehouses and utilities, Avconexpo ensures every design maximizes efficiency, safety, and sustainability.",
  },
  agro: {
    title: "Agro Value Chain",
    subtitle: "From Farm to Market - Adding Value Every Step of the Way.",
    image: "/service-details/horticulture.jpg",
    imageAlt: "Agro Value Chain",
    introTitle: "From Farm to Market",
    highlight: "Farm to market value creation",
    introParagraphs: ["At Avconexpo, we develop Agro-Value Chain projects that ensure crops and livestock do not stop at the farm gate. Instead, they move through storage, processing, value addition, and packaging into markets where they generate real profits."],
    sections: [
      { eyebrow: "Our Approach", title: "Our Agro Value Chain Approach", blocks: [
        { title: "Strengthening Production", items: ["Soil Preparation & Climate Testing - identify what crops and livestock systems are viable in specific regions.", "Crop Planning & Irrigation - match the right crops with water availability, soil health, and market demand.", "Livestock - improve breeds, housing, feed, and veterinary support for consistent yields.", "Technical Guidance - smart technologies and capacity building that align producers with processor requirements."] },
        { title: "Post-Harvest Handling", items: ["Collection centers, cold chains, and warehousing solutions that extend shelf life.", "Efficient transport and distribution networks.", "Packaging that meets export and retail standards."] },
        { title: "Agro-Processing & Industrial Growth", items: ["Design and implement modern processing plants.", "Deploy technologies that reduce waste and improve margins.", "Add income channels through by-product solutions such as bio-energy, animal feed, and fertilizers.", "Food packaging and preservation solutions."] },
        { title: "Market Access & Trade", items: ["Identify real buyers and viable markets.", "Ensure products meet standards and certifications.", "Link producers to regional and global trade channels."] },
      ] },
    ],
    closingText: "We build strong agro ecosystems through modern farming, horticulture, and allied ventures that create value while protecting communities and resources.",
    ctaLabel: "Start Your Agro Project",
  },
  industrial: {
    title: "Industrial Revival & Growth",
    subtitle: "Helping enterprises rediscover potential, overcome operational challenges, and re-emerge stronger.",
    image: "/service-details/sick-industry.jpg",
    imageAlt: "Industrial Revival and Growth",
    introTitle: "Industrial Revival & Growth",
    highlight: "We partner, we fix, we stay",
    introParagraphs: [
      "At Avconexpo, Industrial Revival & Growth service is designed to help enterprises rediscover their potential, overcome operational challenges, and re-emerge as stronger and more competitive players in the market.",
      "From engineering reviews to operational assessments, we do what it takes to drive profitable results.",
    ],
    sections: [
      { eyebrow: "Challenges", title: "Common Critical Pain Points", blocks: [
        { title: "Overall Plant Efficiency", description: "Low Yield, Poor Work-Flow Management, Inline Bottlenecks, Poor Production Planning, Inefficient Human Resources, Misalignment of Man, Machine, Material & Method, and low machine uptime." },
        { title: "Supply-Chain Management", description: "Poor Material Requisition Planning, Inadequate Inventory Management System, Poor Vendor Management, and Poor Distribution & Channel Partner Management." },
        { title: "Quality Management", description: "Unstructured workflows, high rework, lack of clear SOPs, poor coordination, inconsistent performance, poor input material quality, and frequent non-compliance issues." },
        { title: "Market Positioning", description: "Products losing relevance, poor customer connection, or being outcompeted by faster-moving rivals." },
        { title: "Financial Management", description: "Mounting operational costs, high conversion costs, inability to sustain healthy cash flows, and poor debtors and creditors management." },
        { title: "Organisational Management", description: "Poor strategy and planning, management structure, matrices, control and monitoring, procedure manuals, SOPs, and performance management systems." },
      ] },
      { eyebrow: "Approach", title: "Our Revival Approach", description: "We begin with a problem evaluation, considering technical, operational, and process aspects.", blocks: [
        { title: "System Evaluation Audit & Planning", description: "Through problem evaluation analysis, we determine the root cause of underperformance and bridge our findings to strategically renew and grow the company.", items: ["Reviewing production processes, energy usage, and machinery performance.", "Reviewing material and utility balances.", "Analysing manpower productivity and operational workflows.", "Structured energy assessment to benchmark consumption and identify energy-saving opportunities.", "Identification of key opportunity areas, bottlenecks, and process gaps.", "Assessing market relevance, customer segments, and competitive positioning."] },
        { title: "Engineering & Infrastructure Optimisation", description: "We improve the cost and operational efficiency of industrial unit operations during revival.", items: ["Retrofit or replace obsolete and inefficient machinery.", "Smart facility redesigns to minimise bottlenecks and streamline workflows.", "Optimize utility consumption and implement waste reduction systems.", "20-35% reduction in energy wastage.", "15-20% increase in operational efficiency.", "25%+ reduction in overall energy costs."] },
        { title: "Restructuring People and Processes", description: "We align human resources and operational procedures with the evolving needs of a revitalised industrial setup.", items: ["Upskilling the existing workforce.", "Updated instruction manuals and SOPs across production, quality control, and maintenance.", "Performance-based metrics such as KRAs and KPIs for all departments."] },
        { title: "Business Strategy Realigning", description: "We redirect the strategic direction of underperforming industries to regain profitability.", items: ["Aligning goals with market realities and internal strengths.", "Repositioning your brand for better customer connection.", "Exploring diversification opportunities for new revenue streams.", "Developing cost control strategies and restructuring operations."] },
        { title: "Operational Support", description: "If required, Avconexpo provides hands-on operational support, running the plant for six months to one year.", items: ["Implement the revival strategy in real time.", "Ensure systems, SOPs, and teams operate smoothly under new frameworks.", "Hand over a fully stabilised and profitable operation."] },
      ] },
    ],
    closingTitle: "We don't just advise!",
    closingText: "We partner, we fix, and we stay till it works.",
  },
  startup: {
    title: "Startup Accelerator",
    subtitle: "Built by founders, for the founders.",
    image: "/service-details/startup.jpg",
    imageAlt: "Startup Accelerator",
    introTitle: "Built by Founders, for the Founders",
    highlight: "Vision to venture",
    introParagraphs: [
      "Avconexpo is built by practitioners who have walked the startup path themselves. We understand the challenges of starting, building, and scaling businesses because we've experienced them firsthand, across various industries and markets.",
      "Avconexpo's startup accelerator is designed to transform ideas into robust, scalable, and investor-ready businesses. We work with founders closely, offering tailored solutions and expertise to launch and accelerate your startup successfully.",
      "It is the responsibility of our global network, experts, and strategists who understand your sector to provide access to the right opportunities.",
    ],
    sections: [
    ],
    closingText: "From vision to venture, we support startups with structure, technical guidance, and market access to scale faster and sustainably.",
    ctaLabel: "Accelerate Your Startup",
  },
  waste: {
    title: "Waste Management",
    subtitle: "Transforming yesterday's waste into today's energy.",
    image: "/service-details/waste-management.jpg",
    imageAlt: "Waste Management",
    introTitle: "Transforming Waste into Energy",
    highlight: "Waste to wealth",
    introParagraphs: [
      "At Avconexpo, we offer Energy Recovery Technology (ERT) services that convert waste into energy, processing mixed and unsegregated waste while eliminating the need for costly waste segregation at the source.",
      "This process ensures no carbon emissions and no post-process residue. We focus on converting non-recyclable waste to usable recovered energy in an environmentally responsible manner, using scientifically proven methods.",
    ],
    sections: [
      {
        eyebrow: "Technology",
        title: "What Makes ERT Unique",
        comparison: { leftTitle: "Traditional Disposal", rightTitle: "ERT", rows: [["Segregation Required", "No segregation"], ["High Operating costs", "Lower Capex and Opex"], ["Incineration involved releasing toxic smoke", "Pyrolysis which includes clean conversion"], ["Residues remain", "Hardly any residue"], ["Batch Process - Downtime and odour", "Continuous Process - No smell"]] },
        blocks: [
          { title: "Built-in Monitoring", description: "Built-in monitoring and feedback systems for continuous optimization." },
          { title: "Remote Control", description: "Hardly human interface as controlled remotely for safety and efficiency." },
          { title: "No Fire Hazard", description: "No fire hazard, as there is no combustion process." },
          { title: "Minimal Emissions", description: "Hardly any emissions, making the process environmentally responsible." },
          { title: "Optimal Temperature", description: "Temperatures between 350°C to 500°C ensure efficiency and safety." },
        ],
      },
    ],
    closingText: "Avconexpo provides advanced waste management solutions that save cost, ensure compliance, and protect the environment. ERT transforms yesterday's waste into today's energy, protecting communities while powering progress. With us, waste becomes an opportunity for growth.",
  },
  talent: {
    title: "Talent Management Services",
    subtitle: "Empowering businesses with the right talent, in the right role, at the right time.",
    image: "/service-details/talent-management-services.jpg",
    imageAlt: "Talent Management Services",
    introTitle: "Empowering Businesses",
    highlight: "Right talent, right role, right time",
    introParagraphs: [
      "We assist industries and businesses to perform at their best by aligning the right talent with the right role. Future-ready professionals will be in place at the right time; we help achieve efficiency, innovation, and sustainable growth.",
      "At Avconexpo, our journey of providing end-to-end business and technology solutions has enabled us to establish industries, plants, and large-scale projects across diverse sectors. Yet, building infrastructure is only the first step - real growth comes from running factories with skilled, motivated, and future-ready talent.",
      "That is why we introduced Talent Management Services - to ensure organizations have access to the best professionals across technical, managerial, and leadership roles.",
    ],
    sections: [
      { eyebrow: "Approach", title: "Continuous Talent Solutions", blocks: [
        { title: "Human Resource Planning & Talent Alignment", description: "Avconexpo works closely with organizations and industries to map human resource requirements. Every role is aligned with business objectives, ensuring both current operations and future expansion." },
        { title: "Talent Acquisition & Recruitment Solutions", description: "We provide full-cycle hiring solutions - sourcing skilled professionals from specialized roles to leadership positions. With global reach and regional insights, Avconexpo ensures that every hire contributes measurable value." },
        { title: "Workforce Integration & Performance Management", description: "We enable smooth integration with structured onboarding, compliance-ready induction, and performance systems built on KPIs, KRAs, and SOPs. This accelerates readiness, builds accountability, and enhances productivity." },
        { title: "Leadership Development & Succession Planning", description: "Avconexpo strengthens leadership pipelines with experienced consultants and industry experts. We identify high-potential talent, design growth pathways, and provide mentoring support for leadership continuity." },
        { title: "HR Digitalization & Workforce Analytics", description: "Beyond recruitment, we help organizations maximize workforce potential with industry-specific dashboards and real-time visibility into performance, skills, and productivity." },
      ] },
    ],
    closingText: "Our Talent Management Services ensure that every project, plant, and organization has the right talent, with the right skills, in the right roles - creating businesses that are resilient, innovative, and ready for the future.",
    ctaLabel: "Get Talent Solutions",
  },
  supplyChain: {
    title: "Supply-Chain Management",
    subtitle: "End-to-end supply chain solutions from sourcing to delivery.",
    image: "/service-details/trading-sourcing.jpg",
    imageAlt: "Supply-Chain Management",
    introTitle: "Supply-Chain Management",
    highlight: "You ask, we provide",
    introParagraphs: [
      "Avconexpo began by strengthening supply chain management in Africa and has since expanded to a global network, working closely with industries that needed dependable supply chain support to unlock their true potential.",
      "We understood what businesses needed most - consistent quality, reliable timelines, and dependable after-sales support - and built our solutions to deliver exactly that.",
    ],
    sections: [
      { eyebrow: "Network Impact", title: "A Supply Chain Network Impacts Overall Performance", image: "/service-details/supply-chain-illustration.jpg", imageAlt: "Supply Chain Illustration", paragraphs: ["A strong supply chain fuels efficiency, lowers costs, strengthens cash flows, and drives overall business performance.", "Today, Avconexpo has evolved from addressing regional challenges to shaping a global supply chain ecosystem that spans industries and borders. Instead of settling for the way things are, we empower industries with the assurance that when your business needs it, we ensure it is there. You ask, we provide."] },
      { eyebrow: "Solutions", title: "Supply-Chain Management Solution", description: "Avconexpo's Supply Chain Management services provide an end-to-end solution for businesses seeking reliable partners in sourcing, procurement, and logistics. Our expertise ensures efficiency, cost-effectiveness, and high quality throughout the entire supply chain.", blocks: [
        { title: "Sourcing", description: "Sourcing is more than just selecting vendors; it's about building sustainable, transparent supply relationships that reduce risks and enhance your operational efficiency.", items: ["Connecting businesses with pre-vetted manufacturers and suppliers across diverse industries, locally and globally.", "Reducing sourcing cycle time.", "Identifying suppliers who meet the highest standards for quality and reliability.", "Negotiating pricing and terms to ensure optimum value while maintaining product quality.", "Leveraging our extensive global network of pre-qualified manufacturers, vendors, and OEMs."] },
        { title: "Vendor Management", description: "Our comprehensive vendor management service handles contract negotiations and supplier communications.", items: ["Streamlining the vendor management cycle, reducing lead times, and mitigating risks related to delays, defects, or shortages.", "Secure timely availability of critical spares and consumables while ensuring minimum downtime.", "Contract management, compliance verification, and quality assurance.", "Initiate and manage competitive quotes for clear apple-to-apple comparisons."] },
        { title: "Logistics", description: "We offer tailored logistics solutions encompassing freight forwarding, customs clearance, and last-mile delivery.", items: ["Optimized shipping modes for timely and cost-effective delivery.", "Proactive shipment monitoring with real-time updates.", "Issue resolution for any unexpected delays or challenges.", "Full documentation, regulatory compliance, and route optimization."] },
      ], oemPartners: ["Alfa Laval", "ABB", "Bosch", "Thermax", "Kirloskar", "Polycab", "+ Other Vendors"] },
    ],
    closingText: "Partner with Avconexpo for seamless Supply-Chain Management - from supplier discovery to delivery. Let us handle the complexity, so you can focus on growing your business.",
    ctaLabel: "Optimize Your Supply Chain",
  },
};
